export const ADD_TO_CART = 'ADD_TO_CART';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_RECEIVE_PRODUCTS = 'FETCH_RECEIVE_PRODUCTS';
export const FETCH_ERROR_PRODUCTS = 'FETCH_ERROR_PRODUCTS';