export const ADD_TO_CART = 'ADD_TO_CART';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const FETCH_RECEIVE_PRODUCTS = 'FETCH_RECEIVE_PRODUCTS';
export const FETCH_ERROR_PRODUCTS = 'FETCH_ERROR_PRODUCTS';

export const FETCH_PRODUCT_DETAIL = 'FETCH_PRODUCT_DETAIL';
export const FETCH_RECEIVE_PRODUCTDETAIL = 'FETCH_RECEIVE_PRODUCTDETAIL';
export const FETCH_ERROR_PRODUCTDETAIL = 'FETCH_ERROR_PRODUCTDETAIL';